apiVersion: apps/v1
kind: Deployment
metadata:
  name:  weshopify-brands-svc
  namespace: default
  labels:
    app:  weshopify-brands-svc
spec:
  selector:
    matchLabels:
      app: weshopify-brands-svc
  replicas: 1
  template:
    metadata:
      labels:
        app:  weshopify-brands-svc
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
       - name:  weshopify-brands-svc
         image:  narsimybooks/weshopify-brands-svc-img:latest
         ports:
          - containerPort:  5017
         env:
           - name: MONGO_DB_URI
             value: mongodb+srv://mongo:mongo@cluster0.eczp2kn.mongodb.net/?retryWrites=true&w=majority
           - name: MONGO_AUTO_INDEX_CREATION
             value: "true"
           - name: REDIS_SERVER_HOST
             value: weshopify-cache-svc
           - name: REDIS_SERVER_PORT
             value: "6379" 
           - name: REDIS_SERVER_PASSWORD
             value: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
           - name: SERVICE_REGISTRY_HOST
             value: weshopify-registry-svc
           - name: SERVICE_REGISTRY_PORT
             value: "8761"
           - name: AXON_SERVER_HOST
             value: weshopify-axon-server
           - name: AXON_SERVER_PORT
             value: "8124"
           - name: CATEGORIES_SVC_HOST
             value: weshopify-categories-svc
           - name: CATEGORIES_SVC_PORT
             value: "5016"
           - name: ZIPKIN_HOST
             value: weshopify-zipkin-service
           - name: ZIPKIN_PORT
             value: "9411"


      restartPolicy: Always
